# Generated by Django 4.2.4 on 2024-10-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('descripcion_articulo', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajada', models.DateField()),
                ('hora_trabajada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CargoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioArticuloBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_articulos', models.IntegerField()),
                ('en_bodega', models.BooleanField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.articulo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='JornadaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jornada_equipo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jornada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Panol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_panol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('nombre_trabajador', models.CharField(max_length=256)),
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('horas_esperadas_totales', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.cargotrabajador')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.horariotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='RetiroArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_retirada', models.IntegerField()),
                ('fecha_retiro_articulo', models.DateField()),
                ('motivo_retiro_articulo', models.CharField(max_length=2000)),
                ('panol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.panol')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_entrega', models.DateTimeField()),
                ('enviado_panol', models.BooleanField()),
                ('regresado_bodega', models.BooleanField()),
                ('fecha_registro_despacho', models.DateTimeField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.inventarioarticulobodega')),
                ('panol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.panol')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistenciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.asistencia')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='horariotrabajo',
            name='jornada_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.jornadatrabajador'),
        ),
        migrations.AddField(
            model_name='horariotrabajo',
            name='turno_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.turnotrabajador'),
        ),
        migrations.CreateModel(
            name='CapacitacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_capacitacion', models.DateField()),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.capacitacion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada_stock', models.IntegerField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.inventarioarticulobodega')),
                ('panol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.panol')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.categoria'),
        ),
    ]
