# Generated by Django 4.2.4 on 2024-12-17 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('descripcion_articulo', models.CharField(max_length=2000)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPanol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('descripcion_articulo', models.CharField(max_length=2000)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(max_length=256)),
                ('es_renovable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jornada', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquinaria', models.CharField(max_length=255)),
                ('codigo_maquinaria', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineralApp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Panol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_panol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(max_length=256)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.cargo')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.horario')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrabajoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.TextField()),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.maquinaria')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.turno'),
        ),
        migrations.CreateModel(
            name='RetiroArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_retiro', models.DateField(auto_now_add=True)),
                ('fecha_devuelta', models.DateField(blank=True, null=True)),
                ('es_devuelto', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.articulopanol')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.IntegerField()),
                ('horas_esperadas', models.IntegerField(default=40)),
                ('fecha_registro', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.area')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.maquinaria')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.articulobodega')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.panol')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.maquinaria')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='MineralApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.capacitacion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='articulopanol',
            name='panol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.panol'),
        ),
        migrations.AddField(
            model_name='articulobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.bodega'),
        ),
    ]
