# Generated by Django 4.2.4 on 2024-12-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
