# Generated by Django 4.2.4 on 2024-11-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0002_customuser_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HorasTrabajadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trabajador', 'Trabajador'), ('maquinaria', 'Maquinaria')], max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('horas_trabajadas', models.IntegerField()),
                ('mes', models.CharField(max_length=7)),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.maquinaria')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
    ]
