# Generated by Django 4.2.4 on 2024-11-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0003_producto_horastrabajadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trabajador', 'Trabajador'), ('maquinaria', 'Maquinaria')], max_length=20)),
                ('horas_trabajadas', models.PositiveIntegerField()),
                ('fecha_registro', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.area')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.maquinaria')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
        migrations.DeleteModel(
            name='HorasTrabajadas',
        ),
    ]
