# Generated by Django 4.2.4 on 2024-11-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0004_registrohoras_delete_horastrabajadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoras',
            name='tipo',
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='horas_esperadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
