# Generated by Django 4.2.4 on 2024-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0005_remove_registrohoras_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='horas_esperadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
