# Generated by Django 5.1.3 on 2024-11-25 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0006_maquinaria_horas_esperadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_esperadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_trabajadas',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RetiroArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_retiro', models.DateField(default=django.utils.timezone.now)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MineralApp.articulobodega')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.trabajador')),
            ],
        ),
    ]
