# Generated by Django 4.2.4 on 2024-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0007_alter_registrohoras_horas_esperadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
