# Generated by Django 4.2.4 on 2024-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0011_remove_trabajador_horas_esperadas_totales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('En Mantenimiento', 'En Mantenimiento'), ('Operativa', 'Operativa'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Operativa', max_length=20),
        ),
    ]
