# Generated by Django 4.2.4 on 2024-12-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0012_alter_maquinaria_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaria',
            name='horas_esperadas',
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.area'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='codigo_maquinaria',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('OP', 'Operativa'), ('MT', 'En Mantenimiento'), ('FS', 'Fuera de Servicio')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='nombre_maquinaria',
            field=models.CharField(max_length=255),
        ),
    ]
