# Generated by Django 5.1.4 on 2024-12-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0014_alter_maquinaria_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='MineralApp.articulobodega'),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='retiroarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.articulopanol'),
        ),
        migrations.AlterField(
            model_name='retiroarticulo',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='retiroarticulo',
            name='fecha_retiro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
