# Generated by Django 5.1.4 on 2024-12-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineralApp', '0016_alter_movimientoarticulo_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.articulobodega'),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.panol'),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MineralApp.bodega'),
        ),
    ]
